@isTest
        public class RAD_Utils_test
        {
        Public static testMethod void Utilstest1AM()
        {
        Date dt = date.today();
        String tm ='1:00 AM';
        test.startTest();
        RAD_Utils ut = new RAD_Utils();
        RAD_Utils.getCRONExpression(dt,tm);
        
        test.stopTest();
        System.assertEquals(tm,'1:00 AM');
        }
        
        Public static testMethod void Utilstest2AM()
        {
        Date dt = date.today();
        String tm ='2:00 AM';
        test.startTest();
        RAD_Utils ut = new RAD_Utils();
        RAD_Utils.getCRONExpression(dt,tm);
        
        test.stopTest();
         System.assertEquals(tm,'2:00 AM');
        }
        Public static testMethod void Utilstest3AM()
        {
        Date dt = date.today();
        String tm ='3:00 AM';
        test.startTest();
        RAD_Utils ut = new RAD_Utils();
        RAD_Utils.getCRONExpression(dt,tm);
        
        test.stopTest();
         System.assertEquals(tm,'3:00 AM');
        }
        Public static testMethod void Utilstest4AM()
        {
        Date dt = date.today();
        String tm ='4:00 AM';
        test.startTest();
        RAD_Utils ut = new RAD_Utils();
        RAD_Utils.getCRONExpression(dt,tm);
        
        test.stopTest();
         System.assertEquals(tm,'4:00 AM');
        }
        Public static testMethod void Utilstest5AM()
        {
        Date dt = date.today();
        String tm ='5:00 AM';
        test.startTest();
        RAD_Utils ut = new RAD_Utils();
        RAD_Utils.getCRONExpression(dt,tm);
        
        test.stopTest();
         System.assertEquals(tm,'5:00 AM');
        }
        Public static testMethod void Utilstest6AM()
        {
        Date dt = date.today();
        String tm ='6:00 AM';
        test.startTest();
        RAD_Utils ut = new RAD_Utils();
        RAD_Utils.getCRONExpression(dt,tm);
        
        test.stopTest();
         System.assertEquals(tm,'6:00 AM');
        }
        Public static testMethod void Utilstest7AM()
        {
        Date dt = date.today();
        String tm ='7:00 AM';
        test.startTest();
        RAD_Utils ut = new RAD_Utils();
        RAD_Utils.getCRONExpression(dt,tm);
        
        test.stopTest();
         System.assertEquals(tm,'7:00 AM');
        }
        Public static testMethod void Utilstest8AM()
        {
        Date dt = date.today();
        String tm ='8:00 AM';
        test.startTest();
        RAD_Utils ut = new RAD_Utils();
        RAD_Utils.getCRONExpression(dt,tm);
        
        test.stopTest();
         System.assertEquals(tm,'8:00 AM');
        }
        Public static testMethod void Utilstest9AM()
        {
        Date dt = date.today();
        String tm ='9:00 AM';
        test.startTest();
        RAD_Utils ut = new RAD_Utils();
        RAD_Utils.getCRONExpression(dt,tm);
        
        test.stopTest();
         System.assertEquals(tm,'9:00 AM');
        }
        Public static testMethod void Utilstest10AM()
        {
        Date dt = date.today();
        String tm ='10:00 AM';
        test.startTest();
        RAD_Utils ut = new RAD_Utils();
        RAD_Utils.getCRONExpression(dt,tm);
        
        test.stopTest();
         System.assertEquals(tm,'10:00 AM');
        }
        Public static testMethod void Utilstest11AM()
        {
        Date dt = date.today();
        String tm ='11:00 AM';
        test.startTest();
        RAD_Utils ut = new RAD_Utils();
        RAD_Utils.getCRONExpression(dt,tm);
        
        test.stopTest();
         System.assertEquals(tm,'11:00 AM');
        }
        Public static testMethod void Utilstest12AM()
        {
        Date dt = date.today();
        String tm ='12:00 PM';
        test.startTest();
        RAD_Utils ut = new RAD_Utils();
        RAD_Utils.getCRONExpression(dt,tm);
        
        test.stopTest();
         System.assertEquals(tm,'12:00 PM');
        }
        Public static testMethod void Utilstest13AM()
        {
        Date dt = date.today();
        String tm ='1:00 PM';
        test.startTest();
        RAD_Utils ut = new RAD_Utils();
        RAD_Utils.getCRONExpression(dt,tm);
        
        test.stopTest();
        System.assertEquals(tm,'1:00 PM');
        }
        Public static testMethod void Utilstest14AM()
        {
        Date dt = date.today();
        String tm ='2:00 PM';
        test.startTest();
        RAD_Utils ut = new RAD_Utils();
        RAD_Utils.getCRONExpression(dt,tm);
        
        test.stopTest();
         System.assertEquals(tm,'2:00 PM');
        }
        
        Public static testMethod void Utilstest15AM()
        {
        Date dt = date.today();
        String tm ='3:00 PM';
        test.startTest();
        RAD_Utils ut = new RAD_Utils();
        RAD_Utils.getCRONExpression(dt,tm);
        
        test.stopTest();
         System.assertEquals(tm,'3:00 PM');
        }
        Public static testMethod void Utilstest16AM()
        {
        Date dt = date.today();
        String tm ='4:00 PM';
        test.startTest();
        RAD_Utils ut = new RAD_Utils();
        RAD_Utils.getCRONExpression(dt,tm);
        
        test.stopTest();
         System.assertEquals(tm,'4:00 PM');
        }
        Public static testMethod void Utilstest17AM()
        {
        Date dt = date.today();
        String tm ='5:00 PM';
        test.startTest();
        RAD_Utils ut = new RAD_Utils();
        RAD_Utils.getCRONExpression(dt,tm);
        
        test.stopTest();
         System.assertEquals(tm,'5:00 PM');
        }
        Public static testMethod void Utilstest18AM()
        {
        Date dt = date.today();
        String tm ='6:00 PM';
        test.startTest();
        RAD_Utils ut = new RAD_Utils();
        RAD_Utils.getCRONExpression(dt,tm);
        
        test.stopTest();
         System.assertEquals(tm,'6:00 PM');
        }
        Public static testMethod void Utilstest19AM()
        {
        Date dt = date.today();
        String tm ='7:00 PM';
        test.startTest();
        RAD_Utils ut = new RAD_Utils();
        RAD_Utils.getCRONExpression(dt,tm);
        
        test.stopTest();
         System.assertEquals(tm,'7:00 PM');
        }
        Public static testMethod void Utilstest20AM()
        {
        Date dt = date.today();
        String tm ='8:00 PM';
        test.startTest();
        RAD_Utils ut = new RAD_Utils();
        RAD_Utils.getCRONExpression(dt,tm);
        
        test.stopTest();
         System.assertEquals(tm,'8:00 PM');
        }
        Public static testMethod void Utilstest21AM()
        {
        Date dt = date.today();
        String tm ='9:00 PM';
        test.startTest();
        RAD_Utils ut = new RAD_Utils();
        RAD_Utils.getCRONExpression(dt,tm);
        
        test.stopTest();
         System.assertEquals(tm,'9:00 PM');
        }
        Public static testMethod void Utilstest22AM()
        {
        Date dt = date.today();
        String tm ='10:00 PM';
        test.startTest();
        RAD_Utils ut = new RAD_Utils();
        RAD_Utils.getCRONExpression(dt,tm);
        
        test.stopTest();
         System.assertEquals(tm,'10:00 PM');
        }
        Public static testMethod void Utilstest23AM()
        {
        Date dt = date.today();
        String tm ='11:00 PM';
        test.startTest();
        RAD_Utils ut = new RAD_Utils();
        RAD_Utils.getCRONExpression(dt,tm);
        
        test.stopTest();
        System.assertEquals(tm,'11:00 PM');
        }
        Public static testMethod void Utilstest24AM()
        {
        Date dt = date.today();
        String tm ='12:00 AM';
        test.startTest();
        RAD_Utils ut = new RAD_Utils();
        RAD_Utils.getCRONExpression(dt,tm);
        
        test.stopTest();
        System.assertEquals(tm,'12:00 AM');
        }
        
         Public static testMethod void Utilstest25AM()
        {
        Date dt = date.today();
        String tm ='25:00 AM';
        test.startTest();
        RAD_Utils ut = new RAD_Utils();
        RAD_Utils.getCRONExpression(dt,tm);
        
        test.stopTest();
        System.assertEquals(tm,'25:00 AM');
        }
        public static testMethod void loadTest(){
            RAD_Utils.convertStringToDate('11/02/2017 06:10:22');
            RAD_Utils.convertStringToDate('11/02/2017 06:10:22 PM');
            RAD_Utils.convertStringToDate('11/02/2017 06:10');
        }  
        public static testMethod void testLoad() {
            RAD_Utils.loadTest();
            
        }       
                
        }