public class WaitlistTriggerHandler extends TriggerHandler {

  public WaitlistTriggerHandler() {
    this.setMaxLoopCount(1);
  }

    public override void beforeUpdate() {
    
  }
    public override void afterUpdate() {
    
  }
    public override void beforeInsert() {
    
  }
    public override void afterInsert() {
    
  }
    public override void beforeDelete() {
    
  }
    public override void afterDelete() {
    
  }
    public override void afterUndelete() {
    
  }  
}